### ISSUE TITLE
{HELP} Doesnot read kernel config

### ISSUE THREAD

**Issue by sostk** [omnirom/android_build#7]
it shows this error 
`including ./vendor/omni/Android.mk ...
FindEmulator: find: `vendor/omni/charger/images/hdpi': No such file or directory
build/core/tasks/kernel.mk:137: **********************************************************
build/core/tasks/kernel.mk:138: * Kernel source found, but no configuration was defined  *
build/core/tasks/kernel.mk:139: * Please add the TARGET_KERNEL_CONFIG variable to your   *
build/core/tasks/kernel.mk:140: * BoardConfig.mk file                                    *
build/core/tasks/kernel.mk:141: **********************************************************
build/core/Makefile:34: warning: overriding commands for target `/home/sostk/omni/out/target/product/generic/system/lib/libril.so'
build/core/base_rules.mk:319: warning: ignoring old commands for target `/home/sostk/omni/out/target/product/generic/system/lib/libril.so'
build/core/Makefile:34: warning: overriding commands for target `/home/sostk/omni/out/target/product/generic/system/bin/rild'
build/core/base_rules.mk:319: warning: ignoring old commands for target `/home/sostk/omni/out/target/product/generic/system/bin/rild'
build/core/Makefile:34: warning: overriding commands for target `/home/sostk/omni/out/target/product/generic/system/etc/media_codecs_ffmpeg.xml'
build/core/base_rules.mk:319: warning: ignoring old commands for target `/home/sostk/omni/out/target/product/generic/system/etc/media_codecs_ffmpeg.xml'
Starting build with ninja
ninja: Entering directory `.'
ninja: error: unknown target 'bacon', did you mean 'racoon'?
make: *** [ninja_wrapper] Error 1

real	0m37.511s
user	0m54.608s
sys	0m3.200s
sostk@sostk-Lenovo-ideapad-FLEX-4-1470:~/omni$ 
`

**Comment by darkobas** [comment]
you mean brunch find7op ?

**Comment by darkobas** [comment]
You can get help on irc. This is not the place
